version: "3.1"

services:
  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./web/dist:/var/www/html
      - ./nginx/server.conf:/etc/nginx/nginx.conf
    ports:
      - "8888:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  # MongoDB
  db:
    image: mongo:4
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  # MongoDBの管理クライアント(GUI)
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: db